-- Historical path retained for documentation links.
-- Schema authority is now Alembic: python -m backend.migrate
-- Do not mount this file into PostgreSQL initialization.
-- The exact PR #4 baseline is versions/0001_runtime_baseline.sql.
