"""Report route coverage without claiming schema or authorization conformance."""

import argparse
import ast
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/API_IMPLEMENTATION_STATUS.md"
METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def implemented_routes():
    routes = set()
    for path in (ROOT / "backend/app/routers").glob("*.py"):
        module = ast.parse(path.read_text())
        prefix = ""
        for node in module.body:
            if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
                for keyword in node.value.keywords:
                    if keyword.arg == "prefix" and isinstance(keyword.value, ast.Constant):
                        prefix = keyword.value.value
        for node in module.body:
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if (
                    isinstance(decorator, ast.Call)
                    and isinstance(decorator.func, ast.Attribute)
                    and decorator.func.attr in METHODS
                    and decorator.args
                    and isinstance(decorator.args[0], ast.Constant)
                ):
                    routes.add((decorator.func.attr.upper(), prefix + decorator.args[0].value))
    return routes


def render():
    spec = yaml.safe_load((ROOT / "04-API_SPEC.yaml").read_text())
    actual = implemented_routes()
    lines = [
        "# API implementation status", "",
        "Generated by `python scripts/api_inventory.py`. Route presence alone does not prove contract conformance.", "",
        "Sessions and authorized job reads are implemented. Brief capture requires a configured trusted catalog; compilation, approval, delivery processing and financial workflows remain held. The `/api/v1` routes remain transitional. See [workflow validation](WORKFLOW_VALIDATION.md).", "",
        "| Operation | Method | Contract path | Status |",
        "| --- | --- | --- | --- |",
    ]
    contracted = set()
    for path, item in spec["paths"].items():
        for method, operation in item.items():
            if method not in METHODS:
                continue
            route = (method.upper(), path)
            contracted.add(route)
            status = "Route exists; conformance pending" if route in actual else "Pending"
            lines.append(f"| `{operation['operationId']}` | {method.upper()} | `{path}` | {status} |")
    lines += ["", "## Transitional routes", "", "These routes exist outside the target contract; migrate them in subsequent milestones.", ""]
    lines += [f"- `{method} {path}`" for method, path in sorted(actual - contracted)]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    report = render()
    if args.check:
        if not REPORT.exists() or REPORT.read_text() != report:
            raise SystemExit("API inventory is stale; run python scripts/api_inventory.py")
        print("API inventory is current; full contract acceptance remains pending.")
    else:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(report)
        print(f"Wrote {REPORT.relative_to(ROOT)}")
